# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image
FROM node:22-alpine AS builder

# Install pnpm globally
RUN npm install -g pnpm

# Set working directory
WORKDIR /app

# Copy all files
COPY . .

# Install dependencies and build
RUN pnpm install
RUN pnpm run build

# Use a minimal image for runtime
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy built files and node_modules from builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Set environment variable for Jina.ai API key
ENV JINAAI_API_KEY=<your-jinaai-api-key>

# Command to run the server
CMD ["node", "dist/index.js"]